export const categories: string[] = [
    'Animals',
    'Colors',
    'Countries',
    'Tools',
    'Sports',
    'Emotions',
    'Hobbies',
    'Occupations',
    'Musical Instruments',
    'Board Games',
    'Kitchen Appliances',
    'TV Shows',
    'Famous People',
    'Vegetables',
    'Toys',
    'Desserts',
    'Cars',
    'Planets',
    'Shapes',
    'Books',
    'Holidays',
    'Mountains',
    'Flowers',
    'Fruits',
    'Birds',
    'Fish',
    'Reptiles',
    'Insects',
    'Clothing',
    'Beverages',
    'Languages',
    'Famous Landmarks',
    'Furniture',
    'Trees',
    'Sports Equipment',
    'Mythological Creatures',
    'Cartoon Characters',
    'Art Styles',
    'Precious Stones',
    'Dog Breeds',
    'Cat Breeds',
    'Superheroes',
    'Villains',
    'Musical Genres',
    'Sea Creatures',
    'Party Games',
    'Vehicles',
    'Adjectives',
    'Currencies',
    'Elements',
    'Instruments',
    'Gems',
    'Minerals',
    'Rocks',
    'Mountains',
    'Colleges',
    'Chemicals',
    'Shapes',
    'Art Movements',
    'Body Parts',
    'Fish Species',
    'Constellations',
    'Types of Clothing',
    'Flowers',
    'Types of Music',
    'Philosophers',
    'Dog Breeds',
    'Animal Behaviors',
    'Historical Battles',
    'Sports Teams',
    'Ballets',
    'Dance Styles',
    'Historical Monuments',
    'Musical Duos',
    'Chess Pieces',
    'Classical Composers',
    'Island Nations',
    'Seafood',
    'Spices',
    'Fictional Creatures',
    'Toys',
    'Board Games',
    'Comic Book Heroes',
    'Book Genres',
    'Instruments',
    'Famous Speeches',
    'Political Ideologies',
    'Musical Terms',
    'Natural Wonders',
    'Types of Boats',
    'Opera Singers'
];
