import {shuffleArray} from '@shared/functions';

export function getRandomCategories(language: 'en' | 'de', numberOfCategories: number) {
    const categories = language === 'en' ? categoriesEn : categoriesDe;

    return shuffleArray([...categories]).slice(0, numberOfCategories);
}

const categoriesEn: string[] = [
    'Animals',
    'Countries',
    'Tools',
    'Objects',
    'Sports',
    'Emotions',
    'Hobbies',
    'Occupations',
    'Musical Instruments',
    'Board Games',
    'Kitchen Appliances',
    'Vegetables',
    'Food',
    'Toys',
    'Desserts',
    'Cars',
    'Planets',
    'Shapes',
    'Books',
    'Holidays',
    'Hobbies',
    'Mountains',
    'Flowers',
    'Fruits',
    'Fish',
    'Insects',
    'Clothing',
    'Beverages',
    'Furniture',
    'Trees',
    'Sports Equipment',
    'Mythological Creatures',
    'Cartoon Characters',
    'Precious Stones',
    'Dog Breeds',
    'Cat Breeds',
    'Superheroes',
    'Villains',
    'Musical Genres',
    'Sea Creatures',
    'Vehicles',
    'Gems',
    'Chemicals',
    'Shapes',
    'Body Parts',
    'Constellations',
    'Types of Clothing',
    'Flowers',
    'Types of Music',
    'Dance Styles',
    'Historical Monuments',
    'Musical Duos',
    'Bands',
    'Classical Composers',
    'Spices',
    'Fictional Creatures',
    'Toys',
    'Board Games',
    'Natural Wonders'
];

const categoriesDe = [
    'Tiere',
    'Länder',
    'Werkzeuge',
    'Objekte',
    'Sportarten',
    'Emotionen',
    'Hobbys',
    'Berufe',
    'Musikinstrumente',
    'Brettspiele',
    'Küchengeräte',
    'Gemüse',
    'Essen',
    'Spielzeug',
    'Nachtisch',
    'Autos',
    'Planeten',
    'Bücher',
    'Feiertage',
    'Hobbies',
    'Berge',
    'Blumen',
    'Früchte',
    'Insekten',
    'Kleidung',
    'Getränke',
    'Möbel',
    'Sportausrüstung',
    'Mythologische Kreaturen',
    'Zeichentrickfiguren',
    'Edelsteine',
    'Hunderassen',
    'Katzenrassen',
    'Superhelden',
    'Schurken',
    'Musikgenres',
    'Meeresbewohner',
    'Fahrzeuge',
    'Edelsteine',
    'Berge',
    'Körperteile',
    'Fischarten',
    'Sternbilder',
    'Arten von Kleidung',
    'Blumen',
    'Musikrichtungen',
    'Sportmannschaften',
    'Tanzstile',
    'Historische Monumente',
    'Musikduos',
    'Bands',
    'Gewürze',
    'Fiktive Kreaturen',
    'Spielzeug',
    'Brettspiele',
    'Naturwunder'
];
