import {randomInt} from '@shared/functions';

export function getRandomCategory(language: 'en' | 'de') {
    const categories = language === 'en' ? categoriesEn : categoriesDe;

    return categories[randomInt(categories.length)];
}

const categoriesEn: string[] = [
    'Animals',
    'Colors',
    'Countries',
    'Tools',
    'Sports',
    'Emotions',
    'Hobbies',
    'Occupations',
    'Musical Instruments',
    'Board Games',
    'Kitchen Appliances',
    'TV Shows',
    'Famous People',
    'Vegetables',
    'Toys',
    'Desserts',
    'Cars',
    'Planets',
    'Shapes',
    'Books',
    'Holidays',
    'Mountains',
    'Flowers',
    'Fruits',
    'Birds',
    'Fish',
    'Reptiles',
    'Insects',
    'Clothing',
    'Beverages',
    'Languages',
    'Famous Landmarks',
    'Furniture',
    'Trees',
    'Sports Equipment',
    'Mythological Creatures',
    'Cartoon Characters',
    'Art Styles',
    'Precious Stones',
    'Dog Breeds',
    'Cat Breeds',
    'Superheroes',
    'Villains',
    'Musical Genres',
    'Sea Creatures',
    'Party Games',
    'Vehicles',
    'Adjectives',
    'Currencies',
    'Elements',
    'Instruments',
    'Gems',
    'Minerals',
    'Rocks',
    'Mountains',
    'Colleges',
    'Chemicals',
    'Shapes',
    'Art Movements',
    'Body Parts',
    'Fish Species',
    'Constellations',
    'Types of Clothing',
    'Flowers',
    'Types of Music',
    'Philosophers',
    'Dog Breeds',
    'Animal Behaviors',
    'Historical Battles',
    'Sports Teams',
    'Ballets',
    'Dance Styles',
    'Historical Monuments',
    'Musical Duos',
    'Chess Pieces',
    'Classical Composers',
    'Island Nations',
    'Seafood',
    'Spices',
    'Fictional Creatures',
    'Toys',
    'Board Games',
    'Comic Book Heroes',
    'Book Genres',
    'Instruments',
    'Political Ideologies',
    'Musical Terms',
    'Natural Wonders',
    'Types of Boats',
    'Opera Singers'
];

const categoriesDe = [
    'Tiere',
    'Farben',
    'Länder',
    'Werkzeuge',
    'Sportarten',
    'Emotionen',
    'Hobbys',
    'Berufe',
    'Musikinstrumente',
    'Brettspiele',
    'Küchengeräte',
    'TV-Sendungen',
    'Gemüse',
    'Spielzeug',
    'Nachtisch',
    'Autos',
    'Planeten',
    'Formen',
    'Bücher',
    'Feiertage',
    'Berge',
    'Blumen',
    'Früchte',
    'Vögel',
    'Fische',
    'Reptilien',
    'Insekten',
    'Kleidung',
    'Getränke',
    'Sprachen',
    'Berühmte Wahrzeichen',
    'Möbel',
    'Bäume',
    'Sportausrüstung',
    'Mythologische Kreaturen',
    'Zeichentrickfiguren',
    'Kunststile',
    'Edelsteine',
    'Hunderassen',
    'Katzenrassen',
    'Superhelden',
    'Schurken',
    'Musikgenres',
    'Meeresbewohner',
    'Partyspiele',
    'Fahrzeuge',
    'Adjektive',
    'Währungen',
    'Elemente',
    'Instrumente',
    'Edelsteine',
    'Mineralien',
    'Felsen',
    'Berge',
    'Hochschulen',
    'Chemikalien',
    'Formen',
    'Kunstrichtungen',
    'Körperteile',
    'Fischarten',
    'Sternbilder',
    'Arten von Kleidung',
    'Blumen',
    'Musikrichtungen',
    'Philosophen',
    'Hunderassen',
    'Tierverhalten',
    'Historische Schlachten',
    'Sportmannschaften',
    'Ballette',
    'Tanzstile',
    'Historische Monumente',
    'Musikduos',
    'Schachfiguren',
    'Meeresfrüchte',
    'Gewürze',
    'Fiktive Kreaturen',
    'Spielzeug',
    'Brettspiele',
    'Comic-Helden',
    'Buchgenres',
    'Instrumente',
    'Politische Ideologien',
    'Musikalische Begriffe',
    'Naturwunder',
    'Bootsarten',
    'Opernsänger'
];
