name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}} ${{github.sha}}
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with: 
        working-directory: |
          api
          ui
  
    - name: Build API
      run: npm run build
      working-directory: api
    
    - name: Build UI
      run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      working-directory: ui
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          api/dist
          ui/build

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Create Deployment
        id: deploy
        uses: abendigo/create-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          payload: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
