name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{github.ref}} ${{github.sha}}
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
      with: 
        working-directory: |
          api
          ui
  
    - name: Build API
      run: npm run build
      working-directory: api
    
    - name: Build UI
      run: npm run build
      working-directory: ui
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          api/dist
          ui/build
